version: '2'
services:
    web:
      image: innp_app:latest
      volumes:
        - ./innp_app/:/home/innp_app/:rw
      command: "supervisord -c /usr/supervisord.conf -n"
      ports:
        - "8080:80"