version: '2'
services:
    web:
      image: innp_app:latest
      volumes:
        - ./innp_app/:/home/innp_app/:rw
      command: "supervisord -c /usr/supervisord.conf -n"
      ports:
        - "8080:80"

    db:
      image: mysql
      command: mysqld --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ycyy123456
      volumes:
        - ./data/:/var/lib/mysql/:rw
      ports:
        - "3306:3306"