version: '2'
services:
    db:
      image: mysql
      command: mysqld --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ycyy123456
      volumes:
        - ./data/:/var/lib/mysql/:rw
      ports:
        - "3306:3306"